name: 'Continuous Integration'

on:
  push:
    branches:
      - master

  pull_request:
    types:
      - ready_for_review
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install -e .

  unit_tests:
    needs: build
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install -e .
      - run: python -m pytest
